name: Monitor de Preços
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - name: Instalar Dependências
        run: |
          pip install -r requirements.txt
          playwright install chromium
      - name: Rodar Robô
        run: python monitor_precos.py
